// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ajmideMessage.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class ChatMessageResponse_Result;
@class DistinguishMusicMessageResponse_Result;
@class GiftMessageResponse_Result;
@class PluginMessageResponse_Result;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum CMD_TYPE

typedef GPB_ENUM(CMD_TYPE) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  CMD_TYPE_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** 开始直播 */
  CMD_TYPE_CmdTypeStartlive = 0,

  /** 结束直播 */
  CMD_TYPE_CmdTypeEndlive = 1,

  /** 即将结束直播 */
  CMD_TYPE_CmdTypeNeedendlive = 2,

  /** 静音 */
  CMD_TYPE_CmdTypeStartmutelive = 3,

  /** 结束静音 */
  CMD_TYPE_CmdTypeEndmutelive = 4,
};

GPBEnumDescriptor *CMD_TYPE_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL CMD_TYPE_IsValidValue(int32_t value);

#pragma mark - Enum ResponseParseType

/** 当前只有以下4种信息需要解析处理，后期如果有添加，需要更新以下枚举文件 */
typedef GPB_ENUM(ResponseParseType) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  ResponseParseType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** 聊天信息解析 */
  ResponseParseType_ResponseParseTypeChatMessageResponse = 0,

  /** 礼物信息解析 */
  ResponseParseType_ResponseParseTypeGiftMessageResponse = 1,

  /** 插件信息解析 */
  ResponseParseType_ResponseParseTypePluginMessageResponse = 2,

  /** 音乐识别信息解析 */
  ResponseParseType_ResponseParseTypeDistinguishMusicMessageResponse = 3,
};

GPBEnumDescriptor *ResponseParseType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL ResponseParseType_IsValidValue(int32_t value);

#pragma mark - Enum ChatMessageRequest_Msg_Type

typedef GPB_ENUM(ChatMessageRequest_Msg_Type) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  ChatMessageRequest_Msg_Type_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** 文字 */
  ChatMessageRequest_Msg_Type_MsgTypeLabel = 0,

  /** 图片 */
  ChatMessageRequest_Msg_Type_MsgTypeImage = 1,
};

GPBEnumDescriptor *ChatMessageRequest_Msg_Type_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL ChatMessageRequest_Msg_Type_IsValidValue(int32_t value);

#pragma mark - Enum ChatMessageResponse_Result_Msg_Type

typedef GPB_ENUM(ChatMessageResponse_Result_Msg_Type) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  ChatMessageResponse_Result_Msg_Type_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** 文字 */
  ChatMessageResponse_Result_Msg_Type_MsgTypeLabel = 0,

  /** 图片 */
  ChatMessageResponse_Result_Msg_Type_MsgTypeImage = 1,
};

GPBEnumDescriptor *ChatMessageResponse_Result_Msg_Type_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL ChatMessageResponse_Result_Msg_Type_IsValidValue(int32_t value);

#pragma mark - Enum ChatMessageResponse_Result_Role_Type

typedef GPB_ENUM(ChatMessageResponse_Result_Role_Type) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  ChatMessageResponse_Result_Role_Type_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** 普通用户 */
  ChatMessageResponse_Result_Role_Type_RoleTypeUsual = 0,

  /** 主播 */
  ChatMessageResponse_Result_Role_Type_RoleTypeHost = 1,
};

GPBEnumDescriptor *ChatMessageResponse_Result_Role_Type_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL ChatMessageResponse_Result_Role_Type_IsValidValue(int32_t value);

#pragma mark - Enum GiftMessageRequest_Gift_Type

typedef GPB_ENUM(GiftMessageRequest_Gift_Type) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  GiftMessageRequest_Gift_Type_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** 礼物 */
  GiftMessageRequest_Gift_Type_GiftTypeGift = 0,

  /** 打赏 */
  GiftMessageRequest_Gift_Type_GiftTypeMoney = 1,
};

GPBEnumDescriptor *GiftMessageRequest_Gift_Type_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL GiftMessageRequest_Gift_Type_IsValidValue(int32_t value);

#pragma mark - Enum GiftMessageResponse_Result_Gift_Type

typedef GPB_ENUM(GiftMessageResponse_Result_Gift_Type) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  GiftMessageResponse_Result_Gift_Type_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** 礼物 */
  GiftMessageResponse_Result_Gift_Type_GiftTypeGift = 0,

  /** 打赏 */
  GiftMessageResponse_Result_Gift_Type_GiftTypeMoney = 1,
};

GPBEnumDescriptor *GiftMessageResponse_Result_Gift_Type_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL GiftMessageResponse_Result_Gift_Type_IsValidValue(int32_t value);

#pragma mark - Enum PluginMessageRequest_Plugin_Type

typedef GPB_ENUM(PluginMessageRequest_Plugin_Type) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  PluginMessageRequest_Plugin_Type_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** 帖子 */
  PluginMessageRequest_Plugin_Type_PluginTypeTopic = 0,

  /** 投票 */
  PluginMessageRequest_Plugin_Type_PluginTypeVote = 1,

  /** 秒杀 */
  PluginMessageRequest_Plugin_Type_PluginTypeSec = 2,
};

GPBEnumDescriptor *PluginMessageRequest_Plugin_Type_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL PluginMessageRequest_Plugin_Type_IsValidValue(int32_t value);

#pragma mark - Enum PluginMessageResponse_Result_Plugin_Type

typedef GPB_ENUM(PluginMessageResponse_Result_Plugin_Type) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  PluginMessageResponse_Result_Plugin_Type_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** 帖子 */
  PluginMessageResponse_Result_Plugin_Type_PluginTypeTopic = 0,

  /** 投票 */
  PluginMessageResponse_Result_Plugin_Type_PluginTypeVote = 1,

  /** 秒杀 */
  PluginMessageResponse_Result_Plugin_Type_PluginTypeSec = 2,
};

GPBEnumDescriptor *PluginMessageResponse_Result_Plugin_Type_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL PluginMessageResponse_Result_Plugin_Type_IsValidValue(int32_t value);

#pragma mark - AjmideMessageRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface AjmideMessageRoot : GPBRootObject
@end

#pragma mark - ChatMessageRequest

typedef GPB_ENUM(ChatMessageRequest_FieldNumber) {
  ChatMessageRequest_FieldNumber_Type = 1,
  ChatMessageRequest_FieldNumber_Msg = 2,
  ChatMessageRequest_FieldNumber_MsgColor = 3,
  ChatMessageRequest_FieldNumber_Img = 4,
  ChatMessageRequest_FieldNumber_Time = 5,
  ChatMessageRequest_FieldNumber_InsertTime = 6,
};

@interface ChatMessageRequest : GPBMessage

/** 消息类型 */
@property(nonatomic, readwrite) ChatMessageRequest_Msg_Type type;

@property(nonatomic, readwrite, copy, null_resettable) NSString *msg;

@property(nonatomic, readwrite, copy, null_resettable) NSString *msgColor;

@property(nonatomic, readwrite, copy, null_resettable) NSString *img;

@property(nonatomic, readwrite) int32_t time;

@property(nonatomic, readwrite) int32_t insertTime;

@end

/**
 * Fetches the raw value of a @c ChatMessageRequest's @c type property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t ChatMessageRequest_Type_RawValue(ChatMessageRequest *message);
/**
 * Sets the raw value of an @c ChatMessageRequest's @c type property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetChatMessageRequest_Type_RawValue(ChatMessageRequest *message, int32_t value);

#pragma mark - ChatMessageResponse

typedef GPB_ENUM(ChatMessageResponse_FieldNumber) {
  ChatMessageResponse_FieldNumber_ResultArray = 1,
};

@interface ChatMessageResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<ChatMessageResponse_Result*> *resultArray;
/** The number of items in @c resultArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger resultArray_Count;

@end

#pragma mark - ChatMessageResponse_Result

typedef GPB_ENUM(ChatMessageResponse_Result_FieldNumber) {
  ChatMessageResponse_Result_FieldNumber_MsgId = 1,
  ChatMessageResponse_Result_FieldNumber_Type = 2,
  ChatMessageResponse_Result_FieldNumber_Msg = 3,
  ChatMessageResponse_Result_FieldNumber_MsgColor = 4,
  ChatMessageResponse_Result_FieldNumber_Img = 6,
  ChatMessageResponse_Result_FieldNumber_Time = 7,
  ChatMessageResponse_Result_FieldNumber_InsertTime = 8,
  ChatMessageResponse_Result_FieldNumber_Usernick = 9,
  ChatMessageResponse_Result_FieldNumber_Userrole = 10,
  ChatMessageResponse_Result_FieldNumber_Portrait = 11,
};

@interface ChatMessageResponse_Result : GPBMessage

/** 消息ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *msgId;

/** 消息类型 */
@property(nonatomic, readwrite) ChatMessageResponse_Result_Msg_Type type;

@property(nonatomic, readwrite, copy, null_resettable) NSString *msg;

@property(nonatomic, readwrite, copy, null_resettable) NSString *msgColor;

@property(nonatomic, readwrite, copy, null_resettable) NSString *img;

@property(nonatomic, readwrite) int32_t time;

@property(nonatomic, readwrite) int32_t insertTime;

@property(nonatomic, readwrite, copy, null_resettable) NSString *usernick;

/** 用户角色 */
@property(nonatomic, readwrite) ChatMessageResponse_Result_Role_Type userrole;

@property(nonatomic, readwrite, copy, null_resettable) NSString *portrait;

@end

/**
 * Fetches the raw value of a @c ChatMessageResponse_Result's @c type property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t ChatMessageResponse_Result_Type_RawValue(ChatMessageResponse_Result *message);
/**
 * Sets the raw value of an @c ChatMessageResponse_Result's @c type property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetChatMessageResponse_Result_Type_RawValue(ChatMessageResponse_Result *message, int32_t value);

/**
 * Fetches the raw value of a @c ChatMessageResponse_Result's @c userrole property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t ChatMessageResponse_Result_Userrole_RawValue(ChatMessageResponse_Result *message);
/**
 * Sets the raw value of an @c ChatMessageResponse_Result's @c userrole property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetChatMessageResponse_Result_Userrole_RawValue(ChatMessageResponse_Result *message, int32_t value);

#pragma mark - GiftMessageRequest

typedef GPB_ENUM(GiftMessageRequest_FieldNumber) {
  GiftMessageRequest_FieldNumber_Type = 1,
  GiftMessageRequest_FieldNumber_PresenterId = 2,
  GiftMessageRequest_FieldNumber_GiftId = 3,
  GiftMessageRequest_FieldNumber_Count = 4,
  GiftMessageRequest_FieldNumber_GiftCode = 5,
  GiftMessageRequest_FieldNumber_Time = 6,
};

@interface GiftMessageRequest : GPBMessage

/** 礼物类型 */
@property(nonatomic, readwrite) GiftMessageRequest_Gift_Type type;

/** 主持人ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *presenterId;

/** 礼物ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *giftId;

/** 礼物图片 */
@property(nonatomic, readwrite) int32_t count;

/** 礼物code */
@property(nonatomic, readwrite) int32_t giftCode;

/** 发送时间点 秒 */
@property(nonatomic, readwrite) int32_t time;

@end

/**
 * Fetches the raw value of a @c GiftMessageRequest's @c type property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t GiftMessageRequest_Type_RawValue(GiftMessageRequest *message);
/**
 * Sets the raw value of an @c GiftMessageRequest's @c type property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetGiftMessageRequest_Type_RawValue(GiftMessageRequest *message, int32_t value);

#pragma mark - GiftMessageResponse

typedef GPB_ENUM(GiftMessageResponse_FieldNumber) {
  GiftMessageResponse_FieldNumber_ResultArray = 1,
};

@interface GiftMessageResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<GiftMessageResponse_Result*> *resultArray;
/** The number of items in @c resultArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger resultArray_Count;

@end

#pragma mark - GiftMessageResponse_Result

typedef GPB_ENUM(GiftMessageResponse_Result_FieldNumber) {
  GiftMessageResponse_Result_FieldNumber_MsgId = 1,
  GiftMessageResponse_Result_FieldNumber_Type = 2,
  GiftMessageResponse_Result_FieldNumber_GiftNum = 3,
  GiftMessageResponse_Result_FieldNumber_GiftUnit = 4,
  GiftMessageResponse_Result_FieldNumber_GiftImg = 5,
  GiftMessageResponse_Result_FieldNumber_Time = 6,
  GiftMessageResponse_Result_FieldNumber_Usernick = 7,
  GiftMessageResponse_Result_FieldNumber_Portrait = 8,
};

@interface GiftMessageResponse_Result : GPBMessage

/** 消息ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *msgId;

/** 礼物类型 */
@property(nonatomic, readwrite) GiftMessageResponse_Result_Gift_Type type;

/** 礼物数量 */
@property(nonatomic, readwrite) int32_t giftNum;

/** 礼物单位 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *giftUnit;

/** 礼物图片 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *giftImg;

/** 发送时间点 秒 */
@property(nonatomic, readwrite) int32_t time;

/** 用户昵称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *usernick;

/** 用户头像 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *portrait;

@end

/**
 * Fetches the raw value of a @c GiftMessageResponse_Result's @c type property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t GiftMessageResponse_Result_Type_RawValue(GiftMessageResponse_Result *message);
/**
 * Sets the raw value of an @c GiftMessageResponse_Result's @c type property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetGiftMessageResponse_Result_Type_RawValue(GiftMessageResponse_Result *message, int32_t value);

#pragma mark - PluginMessageRequest

typedef GPB_ENUM(PluginMessageRequest_FieldNumber) {
  PluginMessageRequest_FieldNumber_Type = 1,
  PluginMessageRequest_FieldNumber_Name = 2,
  PluginMessageRequest_FieldNumber_Subject = 3,
  PluginMessageRequest_FieldNumber_TopicId = 4,
  PluginMessageRequest_FieldNumber_ProgramId = 5,
  PluginMessageRequest_FieldNumber_PlugImg = 6,
  PluginMessageRequest_FieldNumber_Link = 7,
  PluginMessageRequest_FieldNumber_Time = 8,
};

@interface PluginMessageRequest : GPBMessage

/** 插件类型 */
@property(nonatomic, readwrite) PluginMessageRequest_Plugin_Type type;

/** 插件名称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

/** 插件标题 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *subject;

/** 帖子ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *topicId;

/** 节目ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *programId;

/** 插件图片 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *plugImg;

/** 插件链接地址?这个发送的时候会不会走一个http发送callback 成URL？ */
@property(nonatomic, readwrite, copy, null_resettable) NSString *link;

/** 用户昵称 */
@property(nonatomic, readwrite) int32_t time;

@end

/**
 * Fetches the raw value of a @c PluginMessageRequest's @c type property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t PluginMessageRequest_Type_RawValue(PluginMessageRequest *message);
/**
 * Sets the raw value of an @c PluginMessageRequest's @c type property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetPluginMessageRequest_Type_RawValue(PluginMessageRequest *message, int32_t value);

#pragma mark - PluginMessageResponse

typedef GPB_ENUM(PluginMessageResponse_FieldNumber) {
  PluginMessageResponse_FieldNumber_ResultArray = 1,
};

@interface PluginMessageResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<PluginMessageResponse_Result*> *resultArray;
/** The number of items in @c resultArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger resultArray_Count;

@end

#pragma mark - PluginMessageResponse_Result

typedef GPB_ENUM(PluginMessageResponse_Result_FieldNumber) {
  PluginMessageResponse_Result_FieldNumber_MsgId = 1,
  PluginMessageResponse_Result_FieldNumber_Type = 2,
  PluginMessageResponse_Result_FieldNumber_Name = 3,
  PluginMessageResponse_Result_FieldNumber_Subject = 4,
  PluginMessageResponse_Result_FieldNumber_TopicId = 5,
  PluginMessageResponse_Result_FieldNumber_ProgramId = 6,
  PluginMessageResponse_Result_FieldNumber_PlugImg = 7,
  PluginMessageResponse_Result_FieldNumber_Link = 8,
  PluginMessageResponse_Result_FieldNumber_Usernick = 9,
  PluginMessageResponse_Result_FieldNumber_Portrait = 10,
};

@interface PluginMessageResponse_Result : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *msgId;

/** 插件类型 */
@property(nonatomic, readwrite) PluginMessageResponse_Result_Plugin_Type type;

/** 插件名称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

/** 插件标题 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *subject;

/** 帖子ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *topicId;

/** 节目ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *programId;

/** 插件图片 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *plugImg;

/** 插件链接地址 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *link;

/** 用户昵称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *usernick;

/** 用户头像 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *portrait;

@end

/**
 * Fetches the raw value of a @c PluginMessageResponse_Result's @c type property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t PluginMessageResponse_Result_Type_RawValue(PluginMessageResponse_Result *message);
/**
 * Sets the raw value of an @c PluginMessageResponse_Result's @c type property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetPluginMessageResponse_Result_Type_RawValue(PluginMessageResponse_Result *message, int32_t value);

#pragma mark - DistinguishMusicMessageResponse

typedef GPB_ENUM(DistinguishMusicMessageResponse_FieldNumber) {
  DistinguishMusicMessageResponse_FieldNumber_ResultArray = 1,
};

@interface DistinguishMusicMessageResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<DistinguishMusicMessageResponse_Result*> *resultArray;
/** The number of items in @c resultArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger resultArray_Count;

@end

#pragma mark - DistinguishMusicMessageResponse_Result

typedef GPB_ENUM(DistinguishMusicMessageResponse_Result_FieldNumber) {
  DistinguishMusicMessageResponse_Result_FieldNumber_Duration = 1,
  DistinguishMusicMessageResponse_Result_FieldNumber_MusicOnTime = 2,
  DistinguishMusicMessageResponse_Result_FieldNumber_Ablum = 3,
  DistinguishMusicMessageResponse_Result_FieldNumber_Artist = 4,
  DistinguishMusicMessageResponse_Result_FieldNumber_GiftImg = 5,
};

@interface DistinguishMusicMessageResponse_Result : GPBMessage

/** 时长 */
@property(nonatomic, readwrite) int32_t duration;

/** 音乐所在流中的时间 */
@property(nonatomic, readwrite) int32_t musicOnTime;

/** 专辑名称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ablum;

/** 演唱者 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *artist;

/** 礼物图片 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *giftImg;

@end

#pragma mark - CMDRequest

typedef GPB_ENUM(CMDRequest_FieldNumber) {
  CMDRequest_FieldNumber_Action = 1,
};

@interface CMDRequest : GPBMessage

@property(nonatomic, readwrite) CMD_TYPE action;

@end

/**
 * Fetches the raw value of a @c CMDRequest's @c action property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t CMDRequest_Action_RawValue(CMDRequest *message);
/**
 * Sets the raw value of an @c CMDRequest's @c action property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetCMDRequest_Action_RawValue(CMDRequest *message, int32_t value);

#pragma mark - CMDResponse

typedef GPB_ENUM(CMDResponse_FieldNumber) {
  CMDResponse_FieldNumber_Action = 1,
};

@interface CMDResponse : GPBMessage

@property(nonatomic, readwrite) CMD_TYPE action;

@end

/**
 * Fetches the raw value of a @c CMDResponse's @c action property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t CMDResponse_Action_RawValue(CMDResponse *message);
/**
 * Sets the raw value of an @c CMDResponse's @c action property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetCMDResponse_Action_RawValue(CMDResponse *message, int32_t value);

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
